# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_advisor
    username: postgres
    password: 1234
  freemarker:
    expose-request-attributes: true
    suffix: .ftl
    #  https://stackoverflow.com/questions/53172123/flyway-found-non-empty-schemas-public-without-schema-history-table-use-bas
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.yandex.ru
    username: maicl.svetlov@yandex.ru
    password: unevqrlqmgafiymw
    port: 465
    protocol: smtps
    properties:
      mail:
        debug: true
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

upload.path: /c:/workspace/project/restaurant_advisor/uploads/
recaptcha.secret: 6Ldosm0bAAAAAJCXZgVkciv2zai6rT1hEMybmJo_
server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

