  # https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_advisor
    username: postgres
    password: 1234
  freemarker:
    expose-request-attributes: true
    suffix: .ftl

upload.path: /c:/workspace/project/restaurant_advisor/uploads/
server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true